import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_QUOTATIONS
  FETCH_QUOTATIONS_SUCCESS
  FETCH_QUOTATIONS_FAILURE

  UPDATE_QUOTATION
  UPDATE_QUOTATION_SUCCESS
  UPDATE_QUOTATION_FAILURE

  CREATE_QUOTATION
  CREATE_QUOTATION_SUCCESS
  CREATE_QUOTATION_FAILURE

  FILTER_QUOTATIONS

  GENERATE_QUOTATION
  GENERATE_QUOTATION_SUCCESS
  GENERATE_QUOTATION_FAILURE

  RESET_QUOTATION

`,
  {}
);