import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_EMPLOYEES
  FETCH_EMPLOYEES_SUCCESS
  FETCH_EMPLOYEES_FAILURE

  GET_EMPLOYEE
  GET_EMPLOYEE_SUCCESS
  GET_EMPLOYEE_FAILURE

  CREATE_EMPLOYEE
  CREATE_EMPLOYEE_SUCCESS
  CREATE_EMPLOYEE_FAILURE

  UPDATE_EMPLOYEE
  UPDATE_EMPLOYEE_SUCCESS
  UPDATE_EMPLOYEE_FAILURE

  ENABLE_EMPLOYEE
  ENABLE_EMPLOYEE_SUCCESS
  ENABLE_EMPLOYEE_FAILURE

  DISABLE_EMPLOYEE
  DISABLE_EMPLOYEE_SUCCESS
  DISABLE_EMPLOYEE_FAILURE

  DELETE_EMPLOYEE
  DELETE_EMPLOYEE_SUCCESS
  DELETE_EMPLOYEE_FAILURE

  FILTER_EMPLOYEES

  RESET_EMPLOYEE

`,
  {}
);