export const FETCH_REQUEST_TYPES = {
  MY_REQUESTS: "MY-REQUESTS",
  HOD_PENDING_REQUEST: "HOD-PENDING-REQUESTS",
  HOD_PENDING_ENDORSEMENT_REQUESTS: "HOD-PENDING-ENDORSEMENT-REQUESTS",
  ENDORSED_REQUESTS: "ENDORSED_REQUESTS",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-REQUEST",
  REQUESTS_BY_SUPPLIER: "REQUEST-BY-SUPPLIER",
  DOCUMENTED_REQUESTS_BY_SUPPLIER: "DOCUMENTED-REQUEST-BY-SUPPLIER"
}

export const UPDATE_REQUEST_TYPES = {
  HOD_ENDORSE: "HOD-ENDORSE",
  HOD_CANCEL: "HOD-CANCEL",
  HOD_REJECT: "HOD-REJECT",
  ASSIGN_SUPPLIERS: "ASSIGN-SUPPLIERS",
  UPDATE_UNIT_PRICE: "UPDATE-UNIT-PRICE",
  APPROVE: "APPROVE"
}