export const FETCH_REQUEST_TYPES = {
  MY_REQUESTS: "MY-REQUESTS",
  HOD_PENDING_REQUEST: "HOD-PENDING-REQUESTS",
  HOD_PENDING_REVIEW: "HOD-PENDING-REVIEW",
  HOD_PENDING_ENDORSEMENT_REQUESTS: "HOD-PENDING-ENDORSEMENT-REQUESTS",
  ENDORSED_REQUESTS: "ENDORSED_REQUESTS",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-REQUEST",
  REQUESTS_BY_SUPPLIER: "REQUEST-BY-SUPPLIER",
  DOCUMENTED_REQUESTS_BY_SUPPLIER: "DOCUMENTED-REQUEST-BY-SUPPLIER",
  DEPARTMENT_ENDORSED_REQUESTS: "DEPARTMENT_ENDORSED_REQUESTS",
  ALL_APPROVED_REQUESTS: "ALL_APPROVED_REQUESTS"
}


export const UPDATE_REQUEST_TYPES = {
  HOD_ENDORSE: "HOD_ENDORSE",
  HOD_CANCEL: "HOD_CANCEL",
  HOD_COMMENT: "HOD_COMMENT",
  HOD_APPROVE: "HOD_APPROVE",
  HOD_REVIEW: "HOD_REVIEW",
  GM_APPROVE: "GM_APPROVE",
  GM_COMMENT: "GM_CANCEL",
  GM_CANCEL: "GM_CANCEL",
  ASSIGN_SUPPLIERS: "ASSIGN-SUPPLIERS",
  UPDATE_UNIT_PRICE: "UPDATE-UNIT-PRICE",
  APPROVE: "APPROVE",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-PENDING-ASSIGN-SUPPLIER-REQUESTS"
}

export const FETCH_PETTY_CASH_REQUEST_TYPES = {
  MY_REQUESTS: "MY-REQUESTS",
  HOD_PENDING_REQUEST: "HOD-PENDING-REQUESTS",
  HOD_PENDING_REVIEW: "HOD-PENDING-REVIEW",
  HOD_PENDING_ENDORSEMENT_REQUESTS: "HOD-PENDING-ENDORSEMENT-REQUESTS",
  ENDORSED_REQUESTS: "ENDORSED_REQUESTS",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-REQUEST",
  REQUESTS_BY_SUPPLIER: "REQUEST-BY-SUPPLIER",
  DOCUMENTED_REQUESTS_BY_SUPPLIER: "DOCUMENTED-REQUEST-BY-SUPPLIER",
  GM_PENDING_APPROVAL: "GM_PENDING_APPROVAL",
  PENDING_FUND_ALLOCATION: "PENDING_FUND_ALLOCATION"
}

export const UPDATE_PETTY_CASH_REQUEST_TYPES = {
  HOD_ENDORSE: "HOD_ENDORSE",
  HOD_CANCEL: "HOD_CANCEL",
  HOD_COMMENT: "HOD_COMMENT",
  HOD_APPROVE: "HOD_APPROVE",
  HOD_REVIEW: "HOD_REVIEW",
  ASSIGN_SUPPLIERS: "ASSIGN-SUPPLIERS",
  UPDATE_UNIT_PRICE: "UPDATE-UNIT-PRICE",
  APPROVE: "APPROVE",
  GM_APPROVE: "GM_APPROVE",
  GM_CANCEL: "GM_CANCEL",
  GM_COMMENT: "GM_COMMENT",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-PENDING-ASSIGN-SUPPLIER-REQUESTS"
}


export const FETCH_FLOAT_REQUEST_TYPES = {
  MY_REQUESTS: "MY-REQUESTS",
  HOD_PENDING_REQUEST: "HOD-PENDING-REQUESTS",
  PENDING_APPROVAL: "PENDING-REQUESTS",
  HOD_PENDING_REVIEW: "HOD-PENDING-REVIEW",
  HOD_PENDING_ENDORSEMENT_REQUESTS: "HOD-PENDING-ENDORSEMENT-REQUESTS",
  ENDORSED_REQUESTS: "ENDORSED_REQUESTS",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-REQUEST",
  REQUESTS_BY_SUPPLIER: "REQUEST-BY-SUPPLIER",
  DOCUMENTED_REQUESTS_BY_SUPPLIER: "DOCUMENTED-REQUEST-BY-SUPPLIER",
  PENDING_FUND_ALLOCATION: "PENDING_FUND_ALLOCATION",
  PENDING_GRN: "PENDING_GRN",
  PENDING_DOCUMENT_UPLOAD: "PENDING_DOCUMENT_UPLOAD",
  GM_PENDING_RETIRE: "GM-PENDING-RETIRE",
  AUDITOR_PENDING_RETIRE: "AUDITOR-PENDING_RETIRE",
  MY_AWAITING_RETIREMENT: "MY-AWAITING-RETIREMENT",
  CLOSE_RETIREMENT: "CLOSE-RETIREMENT"
}

export const UPDATE_FLOAT_REQUEST_TYPES = {
  HOD_ENDORSE: "HOD_ENDORSE",
  HOD_CANCEL: "HOD_CANCEL",
  HOD_COMMENT: "HOD_COMMENT",
  HOD_APPROVE: "HOD_APPROVE",
  HOD_REVIEW: "HOD_REVIEW",
  ASSIGN_SUPPLIERS: "ASSIGN-SUPPLIERS",
  UPDATE_UNIT_PRICE: "UPDATE-UNIT-PRICE",
  APPROVE: "APPROVE",
  PROCUREMENT_PENDING_ASSIGN_SUPPLIER_REQUESTS: "PROCUREMENT-PENDING-ASSIGN-SUPPLIER-REQUESTS"
}