import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_SUPPLIERS
  FETCH_SUPPLIERS_SUCCESS
  FETCH_SUPPLIERS_FAILURE

  CREATE_SUPPLIER
  CREATE_SUPPLIER_SUCCESS
  CREATE_SUPPLIER_FAILURE

  UPDATE_SUPPLIER
  UPDATE_SUPPLIER_SUCCESS
  UPDATE_SUPPLIER_FAILURE

  GET_SUPPLIER
  GET_SUPPLIER_SUCCESS
  GET_SUPPLIER_FAILURE

  DELETE_SUPPLIER
  DELETE_SUPPLIER_SUCCESS
  DELETE_SUPPLIER_FAILURE

  SET_SELECTED_SUPPLIERS
  FILTER_SUPPLIERS

  RESET_SUPPLIERS

`,
  {}
);