import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_PAYMENTS
  FETCH_PAYMENTS_SUCCESS
  FETCH_PAYMENTS_FAILURE

  FETCH_PAYMENT
  FETCH_PAYMENT_SUCCESS
  FETCH_PAYMENT_FAILURE

  UPDATE_PAYMENT
  UPDATE_PAYMENT_SUCCESS
  UPDATE_PAYMENT_FAILURE

  CREATE_PAYMENT
  CREATE_PAYMENT_SUCCESS
  CREATE_PAYMENT_FAILURE

  FILTER_PAYMENTS

  RESET_PAYMENT



  FETCH_PAYMENT_DRAFTS
  FETCH_PAYMENT_DRAFTS_SUCCESS
  FETCH_PAYMENT_DRAFTS_FAILURE

  FETCH_PAYMENT_DRAFT
  FETCH_PAYMENT_DRAFT_SUCCESS
  FETCH_PAYMENT_DRAFT_FAILURE

  DELETE_PAYMENT_DRAFT
  DELETE_PAYMENT_DRAFT_SUCCESS
  DELETE_PAYMENT_DRAFT_FAILURE

  UPDATE_PAYMENT_DRAFT
  UPDATE_PAYMENT_DRAFT_SUCCESS
  UPDATE_PAYMENT_DRAFT_FAILURE

  CREATE_PAYMENT_DRAFT
  CREATE_PAYMENT_DRAFT_SUCCESS
  CREATE_PAYMENT_DRAFT_FAILURE

  FILTER_PAYMENT_DRAFTS

  RESET_PAYMENT_DRAFT

`,
  {}
);