import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_FLOAT_REQUESTS
  FETCH_FLOAT_REQUESTS_SUCCESS
  FETCH_FLOAT_REQUESTS_FAILURE

  FETCH_FLOAT_ORDERS
  FETCH_FLOAT_ORDERS_SUCCESS
  FETCH_FLOAT_ORDERS_FAILURE

  FETCH_FLOAT_ORDER
  FETCH_FLOAT_ORDER_SUCCESS
  FETCH_FLOAT_ORDER_FAILURE

  ADD_ITEMS_TO_FLOAT_ORDER
  ADD_ITEMS_TO_FLOAT_ORDER_SUCCESS
  ADD_ITEMS_TO_FLOAT_ORDER_FAILURE

  RETIRE_FLOAT_ORDER
  RETIRE_FLOAT_ORDER_SUCCESS
  RETIRE_FLOAT_ORDER_FAILURE

  UPDATE_FLOAT_ORDER_STATUS
  UPDATE_FLOAT_ORDER_STATUS_SUCCESS
  UPDATE_FLOAT_ORDER_STATUS_FAILURE

  FETCH_MY_FLOAT_REQUESTS
  FETCH_MY_FLOAT_REQUESTS_SUCCESS
  FETCH_MY_FLOAT_REQUESTS_FAILURE

  GET_FLOAT_REQUEST
  GET_FLOAT_REQUEST_SUCCESS
  GET_FLOAT_REQUEST_FAILURE

  CREATE_FLOAT_REQUEST
  CREATE_FLOAT_REQUEST_SUCCESS
  CREATE_FLOAT_REQUEST_FAILURE

  UPDATE_FLOAT_REQUEST
  UPDATE_FLOAT_REQUEST_SUCCESS
  UPDATE_FLOAT_REQUEST_FAILURE

  UPDATE_SINGLE_FLOAT_REQUEST
  UPDATE_SINGLE_FLOAT_REQUEST_SUCCESS
  UPDATE_SINGLE_FLOAT_REQUEST_FAILURE

  DELETE_FLOAT_REQUEST
  DELETE_FLOAT_REQUEST_SUCCESS
  DELETE_FLOAT_REQUEST_FAILURE

  ALLOCATE_FUNDS_TO_FLOAT_REQUEST
  ALLOCATE_FUNDS_TO_FLOAT_REQUEST_SUCCESS
  ALLOCATE_FUNDS_TO_FLOAT_REQUEST_FAILURE

  SET_SELECTED_FLOAT_REQUESTS

  FILTER_FLOAT_REQUESTS

  RESET_FLOAT_REQUEST

`,
  {}
);