import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_FLOAT_REQUESTS
  FETCH_FLOAT_REQUESTS_SUCCESS
  FETCH_FLOAT_REQUESTS_FAILURE

  FETCH_MY_FLOAT_REQUESTS
  FETCH_MY_FLOAT_REQUESTS_SUCCESS
  FETCH_MY_FLOAT_REQUESTS_FAILURE

  GET_FLOAT_REQUEST
  GET_FLOAT_REQUEST_SUCCESS
  GET_FLOAT_REQUEST_FAILURE

  CREATE_FLOAT_REQUEST
  CREATE_FLOAT_REQUEST_SUCCESS
  CREATE_FLOAT_REQUEST_FAILURE

  UPDATE_FLOAT_REQUEST
  UPDATE_FLOAT_REQUEST_SUCCESS
  UPDATE_FLOAT_REQUEST_FAILURE

  UPDATE_SINGLE_FLOAT_REQUEST
  UPDATE_SINGLE_FLOAT_REQUEST_SUCCESS
  UPDATE_SINGLE_FLOAT_REQUEST_FAILURE

  DELETE_FLOAT_REQUEST
  DELETE_FLOAT_REQUEST_SUCCESS
  DELETE_FLOAT_REQUEST_FAILURE

  ALLOCATE_FUNDS_TO_FLOAT_REQUEST
  ALLOCATE_FUNDS_TO_FLOAT_REQUEST_SUCCESS
  ALLOCATE_FUNDS_TO_FLOAT_REQUEST_FAILURE

  SET_SELECTED_FLOAT_REQUESTS

  RESET_FLOAT_REQUEST

`,
  {}
);