import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_COMMENTS
  FETCH_COMMENTS_SUCCESS
  FETCH_COMMENTS_FAILURE

  CREATE_COMMENT
  CREATE_COMMENT_SUCCESS
  CREATE_COMMENT_FAILURE

  CREATE_COMMENT_WITH_CANCEL
  CREATE_COMMENT_WITH_CANCEL_SUCCESS
  CREATE_COMMENT_WITH_CANCEL_FAILURE

  RESET_COMMENT

  SET_NEW_COMMENT

`,
  {}
);