import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_DEPARTMENTS
  FETCH_DEPARTMENTS_SUCCESS
  FETCH_DEPARTMENTS_FAILURE

  GET_DEPARTMENT
  GET_DEPARTMENT_SUCCESS
  GET_DEPARTMENT_FAILURE

  CREATE_DEPARTMENT
  CREATE_DEPARTMENT_SUCCESS
  CREATE_DEPARTMENT_FAILURE

  UPDATE_DEPARTMENT
  UPDATE_DEPARTMENT_SUCCESS
  UPDATE_DEPARTMENT_FAILURE

  DELETE_DEPARTMENT
  DELETE_DEPARTMENT_SUCCESS
  DELETE_DEPARTMENT_FAILURE

  RESET_DEPARTMENT

`,
  {}
);