import { createTypes } from "reduxsauce";

export default createTypes(
  `
  FETCH_REQUEST_CATEGORIES
  FETCH_REQUEST_CATEGORIES_SUCCESS
  FETCH_REQUEST_CATEGORIES_FAILURE

  CREATE_REQUEST_CATEGORY
  CREATE_REQUEST_CATEGORY_SUCCESS
  CREATE_REQUEST_CATEGORY_FAILURE

  UPDATE_REQUEST_CATEGORY
  UPDATE_REQUEST_CATEGORY_SUCCESS
  UPDATE_REQUEST_CATEGORY_FAILURE

  DELETE_REQUEST_CATEGORY
  DELETE_REQUEST_CATEGORY_SUCCESS
  DELETE_REQUEST_CATEGORY_FAILURE

  SET_REQUEST_CATEGORY

  RESET_REQUEST_CATEGORY

`,
  {}
);